// SPDX-License-Identifier: MIT
pragma solidity ^0.8.28;

import {Test} from "forge-std/Test.sol";
import {IdentityRegistry} from "../src/IdentityRegistry.sol";
import {ValidationRegistry} from "../src/ValidationRegistry.sol";
import {AttestcoinValidator} from "../src/AttestcoinValidator.sol";
import {IValidationRegistry} from "../src/IValidationRegistry.sol";
import {INativeQueryVerifier} from "../src/vendor/INativeQueryVerifier.sol";

/// Both fixtures are REAL proofs, generated by the live Creditcoin prover, for two real USDC
/// transfers that sit in the SAME Ethereum mainnet block (25,971,533). Same Merkle root, same
/// continuity proof, same attestation. One moved 45.00 USDC. One reverted and moved nothing.
///
/// `0x0FD2` is mocked to return true for BOTH, because that is what it actually does. That was
/// verified against the live precompile before this test was written.
contract WarrantTest is Test {
    address constant PRECOMPILE = 0x0000000000000000000000000000000000000FD2;
    address constant USDC       = 0xA0b86991c6218b36c1d19D4a2e9Eb0cE3606eB48;

    IdentityRegistry   identity;
    ValidationRegistry registry;
    AttestcoinValidator warrant;
    uint256 agentId;
    string  json;

    event RejectedRevertedTransaction(bytes32 indexed requestHash, bytes32 indexed txKey);

    function setUp() public {
        identity = new IdentityRegistry();
        registry = new ValidationRegistry(identity);
        warrant  = new AttestcoinValidator(IValidationRegistry(address(registry)), 3, USDC);
        agentId  = identity.register("https://example.invalid/agent.json");
        json     = vm.readFile("test/fixtures.json");
        // The precompile says "this transaction is in that block" for both. It is right both times.
        vm.mockCall(PRECOMPILE, bytes(""), abi.encode(true));
    }

    function _claim(string memory key, address payer, address payee, uint256 minAmount)
        internal view returns (AttestcoinValidator.Claim memory c)
    {
        c.blockHeight = uint64(vm.parseJsonUint(json, string.concat(".", key, ".blockHeight")));
        c.txBytes     = vm.parseJsonBytes(json, string.concat(".", key, ".txBytes"));
        c.payer = payer; c.payee = payee; c.minAmount = minAmount;
        c.merkleProof = INativeQueryVerifier.MerkleProof(bytes32(0), new INativeQueryVerifier.MerkleProofEntry[](0));
        c.continuityProof = INativeQueryVerifier.ContinuityProof(bytes32(0), new bytes32[](0));
    }

    function _request(bytes32 h) internal {
        registry.validationRequest(address(warrant), agentId, "ipfs://job", h);
    }

    /// A real, successful 45.00 USDC payment validates to 100.
    function test_RealPayment_Validates100() public {
        bytes32 h = keccak256("job-good");
        _request(h);
        warrant.prove(h, _claim("good",
            0x466Ba3EdD0783B0e0E675B50E7E59396B0433064,
            0xFF0FccDF925FbB868f8Fb2d055388F7129f14111,
            45_000_000));
        (,, uint8 response,,,) = registry.getValidationStatus(h);
        assertEq(response, 100, "real payment should validate");
    }

    /// THE POINT. A proof of a REVERTED transaction is a valid proof. It is not a payment.
    function test_RevertedPayment_Rejected() public {
        bytes32 h = keccak256("job-bad");
        _request(h);
        vm.expectEmit(true, false, false, false);
        emit RejectedRevertedTransaction(h, bytes32(0));
        warrant.prove(h, _claim("bad",
            0x102b412B7Bd6d2E79A52e6b5cf2be8f35eE30bed,
            0xef252Ffa4dce6D39329CC83F084Fb67977beeaA1,
            13_000_000));
        (,, uint8 response,,,) = registry.getValidationStatus(h);
        assertEq(response, 0, "a reverted transfer must never validate");
    }

    /// A second settlement on the same proof must not be possible.
    function test_Replay_Rejected() public {
        bytes32 h1 = keccak256("job-good"); _request(h1);
        warrant.prove(h1, _claim("good",
            0x466Ba3EdD0783B0e0E675B50E7E59396B0433064,
            0xFF0FccDF925FbB868f8Fb2d055388F7129f14111, 45_000_000));
        bytes32 h2 = keccak256("job-good-again"); _request(h2);
        warrant.prove(h2, _claim("good",
            0x466Ba3EdD0783B0e0E675B50E7E59396B0433064,
            0xFF0FccDF925FbB868f8Fb2d055388F7129f14111, 45_000_000));
        (,, uint8 r2,,,) = registry.getValidationStatus(h2);
        assertEq(r2, 0, "replayed proof must not validate twice");
    }

    /// The claimed payee must match the log. The caller's assertion is not evidence.
    function test_WrongPayee_Rejected() public {
        bytes32 h = keccak256("job-wrong-payee"); _request(h);
        warrant.prove(h, _claim("good",
            0x466Ba3EdD0783B0e0E675B50E7E59396B0433064,
            address(0xdeadbeef), 45_000_000));
        (,, uint8 response,,,) = registry.getValidationStatus(h);
        assertEq(response, 0, "payee binding must hold");
    }
}
